add: levels/flow: more interactive control flow
hacklab:              avoid set -e with '|| return 0' after call to levels/flow
flow:                 first, check for existing level containers
flow:                 then, (level_start in background) and print_story_or_skip
print_story_or_skip:  wait for level_start
tmux_session:         no changes
evaluation:           switch to new ip plan, better dialogs, clean up 'ausgabe.log'
allow_retry n:        allow user to play  more attempts
clean_up:             (level_stop in background)
upload_score:         meanwhile, ask user to upload points to nibelung.hs-worms.de

diff --git a/hacklab b/hacklab
--- a/hacklab
+++ b/hacklab
@@ -1,6 +1,7 @@
 #!/bin/bash
 
-#set -eEuo pipefail                      # make script fail on any errors/return!=0
+set -a                                  # exports all env variables to child procs
+set -eEuo pipefail                      # make script fail on any errors/return!=0
 [ $# -ge 1 ] && [ $1 = "v" ] && set -x  # VERY verbose, prints every step before its execution
 
 # color variables
@@ -100,8 +101,8 @@ function networks() {
 	echo -ne "\nPlease choose a level: "
     read -n 1 menuinput
     case $menuinput in
-	1)  ./levels/students/networks/01/flow          ;;
-	2)  ./levels/students/networks/02/flow          ;;
+	1)  ./levels/students/networks/01/flow || return 0 ;;
+	2)  ./levels/students/networks/02/flow || return 0 ;;
 	3) echo -e "\nyou chose level 3"                ;;
 	4) echo -e "\nyou chose level 4"                ;;
 	5) echo -e "\nyou chose level 5"                ;;
diff --git a/levels/students/networks/01/evaluation b/levels/students/networks/01/evaluation
--- a/levels/students/networks/01/evaluation
+++ b/levels/students/networks/01/evaluation
@@ -2,23 +2,24 @@
 
 # determine if the attack was successful + award points
 
-packets=$(grep -c "10.2.1.3 → 10.2.1.2     ICMP 42 Echo (ping) reply" ausgabe.log) 	#to determine if the correct packets was sent with the correct IP-adress
-test=$(grep -c "ICMP 42" ausgabe.log)													#to determine if the correct packets was sent
+                                                                                                # '|| return 0' avoids exiting due to 'set -e' flag
+packets=$(grep -c "10.2.1.3 → 10.2.1.2     ICMP 42 Echo (ping) reply" ausgabe.log || exit 0 ) # determine if 10.2.1.3 replied to a spoofed ICMP42 request
+test=$(grep -c "ICMP 42" ausgabe.log || exit 0 )                                              # determine if any ICMP42 packets have been sent at all 
 
 if [ $packets -eq 7 ]; then
     points=10
 	print_colored_ascii ../../../../ressources/ascii/win.txt
-    echo "Wow! Mission accomplished. 10 points.\n"
+    echo -e "Wow! Mission accomplished. 10 points.\n"
 elif [ $packets -ne 7 ] && [ $test -ne 0 ]; then
     points=7
 	print_colored_ascii ../../../../ressources/ascii/insufficient.txt
-	echo "You didn't send the requested number of packet. But still, you get 7 points for that!"
-    [ $packets -lt 7 ] && echo "You only sent $packets packets. Try again.\n"
-    [ $packets -gt 7 ] && echo "You already sent $packets packets. Try again.\n"
+	echo "You didn't send the requested number of packets. But still, you get 7 points for that!"
+    [ $packets -lt 7 ] && echo -e "You only sent $packets packets. Try again.\n"
+    [ $packets -gt 7 ] && echo -e "You already sent $packets packets. Try again.\n"
 else 
     points=0
 	print_colored_ascii ../../../../ressources/ascii/lost.txt
-    echo "Sorry, but you didn't fulfill the task at hand. 0 points, sorry. Try again!\n"
+    echo -e "Seems like you didn't fulfill the task at hand. 0 points, sorry. Try again!\n"
 fi
 
->ausgabe.log                                                                            #clean up the file 
+>ausgabe.log                                                                                    # clean up ausgabe.log after every run 
diff --git a/levels/students/networks/01/flow b/levels/students/networks/01/flow
--- a/levels/students/networks/01/flow
+++ b/levels/students/networks/01/flow
@@ -1,27 +1,27 @@
 #!/bin/bash
-
+set -e
 export module=networks
 export level=1
 
 cd $(dirname "$0")
 PATH=$PATH:$(dirname "$0")
+
+echo -e "\n\nCheck for existing containers..."; sleep .5
+lxc info $module-lvl01-$USER-c01 &> /dev/null && ( echo -e "Error: wait for containers to be removed.\n" && (level_stop $module $level 3 &) && exit 1 )
+lxc info $module-lvl01-$USER-c02 &> /dev/null && ( echo -e "Error: wait for containers to be removed.\n" && (level_stop $module $level 3 &) && exit 1 )
+lxc info $module-lvl01-$USER-c03 &> /dev/null && ( echo -e "Error: wait for containers to be removed.\n" && (level_stop $module $level 3 &) && exit 1 )
+
 (level_start $module $level 3 &)            # initiate level infrastructure
 
 . print_story_or_skip                       # y: story time, n: skip
 
-echo -ne "\nyou chose level $level. starting..."
-while : ; do
-    echo -n "."; sleep .5
-    state=$( lxc info $module-lvl01-c03-$USER 2> /dev/null | grep '(global)' | sed s/'.*('/'('/ ) &> /dev/null
-    [ "$state" = '(global)' ] && break
-done
+./tmux_session; clear                       # <- actual gameplay - create different windows, DON'T SOURCE IT
+. ./evaluation                              # needs to be sourced (with '.') to retrieve points
+. allow_retry 3
 
-./tmux_session; clear                       # <- actual gameplay - create different windows
-. ./evaluation                              # needs to be sourced (with '.') to retrieve points 
-. allow_retry
-. upload_score_to_nibelung $module $level   # upload + authentication
+rm ausgabe.log                              # clean up first...
+(level_stop $module $level 3 &)             # ... and remove level infrastructure
 
-rm ausgabe.log                              # clean up
-(level_stop $module $level 3 &)             # remove level infrastructure
+. upload_score_to_nibelung $module $level   # upload + authentication (after clean up to save time)
 
 exit 0
diff --git a/levels/students/networks/02/flow b/levels/students/networks/02/flow
--- a/levels/students/networks/02/flow
+++ b/levels/students/networks/02/flow
@@ -5,24 +5,22 @@ export level=2
 
 cd $(dirname "$0")
 PATH=$PATH:$(dirname "$0")
-echo -e "\nyou chose level $level. starting..."
+
+echo -e "\n\nCheck for existing containers..."; sleep .5
+lxc info $module-lvl02-$USER-c01 &> /dev/null && ( echo -e "Error: wait for containers to be removed.\n" && (level_stop $module $level 3 &) && exit 1 )
+lxc info $module-lvl02-$USER-c02 &> /dev/null && ( echo -e "Error: wait for containers to be removed.\n" && (level_stop $module $level 3 &) && exit 1 )
+lxc info $module-lvl02-$USER-c03 &> /dev/null && ( echo -e "Error: wait for containers to be removed.\n" && (level_stop $module $level 3 &) && exit 1 )
+
 (level_start $module $level 3 &)            # initiate level infrastructure
 
 . print_story_or_skip                       # y: story time, n: skip
 
-echo -ne "\nyou chose level $level. starting..."
-while : ; do
-    echo -n "."; sleep .5
-    state=$( lxc info $module-lvl01-c03-$USER 2> /dev/null | grep '(global)' | sed s/'.*('/'('/ ) &> /dev/null
-    [ "$state" = '(global)' ] && break
-done
-
-tmux_session; clear                         # <- actual gameplay - create different windows
+./tmux_session; clear                       # <- actual gameplay - create different windows, DON'T SOURCE IT
 . ./evaluation                              # needs to be sourced (with '.') to retrieve points 
 . allow_retry                               # allows user to play again without destructing containers
 . upload_score_to_nibelung $module $level   # upload + authentication
 
-#end tmux session                           # clean up
+# end tmux session                          # clean up
 (level_stop $module $level 3 &)             # remove level infrastructure
 
 exit 0
