add: retry upload upon error, clean-up artifacts, add return codes

diff --git a/database/upload_score_to_database b/database/upload_score_to_database
--- a/database/upload_score_to_database
+++ b/database/upload_score_to_database
@@ -7,7 +7,8 @@ function pushDatasetToServer() {
     if [ -f localDataset.txt.gpg ]; then                                        #checks if the file exists
         timeStamp=$(date +%s)
         echo "sending dataset..."
-        scp ./localDataset.txt.gpg hacklab@10.215.33.91:/home/hacklab/uploadedFiles/datasetHacklab-${timeStamp}-${RANDOM}.txt.gpg       #copies the encrypted file to the database
+        scp ./localDataset.txt.gpg hacklab@10.215.33.91:/home/hacklab/uploadedFiles/datasetHacklab-${timeStamp}-${RANDOM}.txt.gpg || return 1       #copies the encrypted file to the database
+        rm ./localDataset.txt.gpg 2> /dev/null
     fi
 }
 
@@ -19,7 +20,8 @@ case $userInput in
         . authentication &&                                                                                        
         echo "$email;$(date +%c);$1;Level $2;$points"                                                               `#text we want to add to database`\
         | gpg -e --always-trust -a -r 590659F58937BD0A763D1DCDD07DBD27DEB068CF > localDataset.txt.gpg &&            `#encrypts the text with the public key of the database`\
-        pushDatasetToServer ;;     
-    N|n) return 0 ;;
-    *) echo -e "\nWrong option\n" ; upload;;
+        pushDatasetToServer && echo -e "Upload successful.\n" || \
+        ( echo -e "Warning: Upload failed. Retry.\n"; . upload_score_to_database $module $level ) ;;
+    N|n) echo ""; return 0 ;;
+    *) echo -e "\nWrong option\n" ; upload_score_to_database $module $level ;;
 esac
