fix: level01

diff --git a/levels/students/networks/01/evaluation b/levels/students/networks/01/evaluation
--- a/levels/students/networks/01/evaluation
+++ b/levels/students/networks/01/evaluation
@@ -1,29 +1,18 @@
 #!/bin/bash
 
-# SPDX-FileCopyrightText: 2022 Bassam-Khaled Thiab <inf3891@hs-worms.de>
-# SPDX-FileCopyrightText: 2022 Dominic Meyer <inf3644@hs-worms.de>
-# SPDX-FileCopyrightText: 2022 Felix Rheinheimer <felix.rheinheimer@hs-worms.de>
-# SPDX-FileCopyrightText: 2022 Jean-Arole Fotsing <inf3608@hs-worms.de>
-# SPDX-FileCopyrightText: 2022 Katrin Vollhardt <inf3493@hs-worms.de>
-# SPDX-FileCopyrightText: 2022 Steve Landry Tchamabe <infXXXX@hs-worms.de>
-# SPDX-FileCopyrightText: 2022 Syed Saad-Ullah <inf3664@hs-worms.de>
-# SPDX-FileCopyrightText: 2022 Thierry-Junior Djeutchou-Njieyong <inf3494@hs-worms.de>
-#
-# SPDX-License-Identifier: GPL-3.0-or-later
-
 # determine if the attack was successful + award points
                                                                                                 # '|| return 0' avoids exiting due to 'set -e' flag
-packets=$(grep -c "10.2.1.3 → 10.2.1.2     ICMP 42 Echo (ping) reply" ausgabe.log || exit 0 )   # determine if 10.2.1.3 replied to a spoofed ICMP42 request
-test=$(grep -c "ICMP 42" ausgabe.log || exit 0 )                                                # determine if any ICMP42 packets have been sent at all 
+packets=$(grep -c "10.2.1.3 → 10.2.1.2     ICMP 42 Echo (ping) reply" control.log || exit 0 )   # determine if 10.2.1.3 replied to a spoofed ICMP42 request
+test=$(grep -c "ICMP 42" control.log || exit 0 )                                                # determine if any ICMP42 packets have been sent at all 
 
 if [ $packets -eq 7 ]; then
-    points=10
+    points="$(( 10 - $try ))"
 	print_colored_ascii ../../../../ressources/ascii/win.txt
-    echo -e "Wow! Mission accomplished. 10 points.\n"
+    echo -e "Wow! Mission accomplished. $points points.\n"
 elif [ $packets -ne 7 ] && [ $test -ne 0 ]; then
-    points=7
+    points="$(( 5 - $try ))"
 	print_colored_ascii ../../../../ressources/ascii/insufficient.txt
-	echo "You didn't send the requested number of packets. But still, you get 7 points for that!"
+	echo "You didn't send the requested number of packets. But still, you get $points points for that!"
     [ $packets -lt 7 ] && echo -e "You only sent $packets packets. Try again.\n"
     [ $packets -gt 7 ] && echo -e "You already sent $packets packets. Try again.\n"
 else 
@@ -32,4 +21,4 @@ else
     echo -e "Seems like you didn't fulfill the task at hand. 0 points, sorry. Try again!\n"
 fi
 
->ausgabe.log                                                                                    # clean up ausgabe.log after every run 
+>control.log                                                                                    # clean up control.log after every run 
