fix: minor errors in scripts/print_colored_ascii

diff --git a/scripts/print_colored_ascii b/scripts/print_colored_ascii
--- a/scripts/print_colored_ascii
+++ b/scripts/print_colored_ascii
@@ -1,21 +1,21 @@
+#!/bin/bash
+
 blink=`echo -en "\e[5m"`
 green=`echo -en "\e[32m"`
 purple=`echo -en "\e[35m"`
 default=`echo -en "\e[39m"`
 
-clear
-file=$(readlink -f "$1")
+file=$(readlink -f $1)
 file_name=$(basename $file)
-if [ $file_name = win.txt ] || [ $file_name = insufficient.txt ] ; then
-   while IFS= read -r line;
-      do #a full file will be printed
-         echo "${blink}${green}$line${default}"         
-      done <$file
-elif [ $file_name = lost.txt ] ; then
-   while IFS= read -r line;
-   do #a full file will be printed
-         echo "${blink}${purple}$line${default}"         
-   done <$file
-else
-   echo "Error in printing colored_ascii.sh file when called from $file"
-fi
+
+if [ "$file_name" = "win.txt" ] || [ "$file_name" = "insufficient.txt" ]; then
+    while IFS= read -r line; do                                             # print each line from $file
+        echo "${blink}${green}$line${default}"                              # apply color + reset to default
+    done <$file
+elif [ "$file_name" = "lost.txt" ]; then
+    while IFS= read -r line; do                                             # print each line from $file
+        echo "${blink}${purple}$line${default}"                             # apply color + reset to default
+    done <$file
+else echo "[$0] Error: invalid parameter: $@"; exit 1; fi
+
+setterm -blink off                                                          # reset blinking letters
